project_name: malice
version: 2


before:
  hooks:
    - go mod tidy
    - curl -L https://github.com/EgeBalci/sgn/releases/download/v2.0.1/sgn_linux_amd64_2.0.1.zip -o /tmp/sgn_linux.zip
      unzip /tmp/sgn_linux.zip -d server/assets/linux
      rm /tmp/sgn_linux.zip

      # Download and extract sgn Windows zip
      curl -L https://github.com/EgeBalci/sgn/releases/download/v2.0.1/sgn_windows_amd64_2.0.1.zip -o /tmp/sgn_windows.zip
      unzip /tmp/sgn_windows.zip -d server/assets/windows
      rm /tmp/sgn_windows.zip

      # Download malefic for Windows
      curl -L https://github.com/chainreactors/malefic/releases/download/v0.0.3/malefic-mutant-x86_64-pc-windows-msvc.exe -o server/assets/windows/malefic-mutant.exe

      # Download malefic for Linux
      curl -L https://github.com/chainreactors/malefic/releases/download/v0.0.3/malefic-mutant-x86_64-unknown-linux-musl -o server/assets/linux/malefic-mutant
      curl -L https://github.com/chainreactors/malefic/releases/download/v0.0.3/malefic-mutant-x86_64-unknown-linux-musl -o server/assets/windows/malefic-mutant
      chmod +x server/assets/linux/malefic-mutant


builds:
  -
    main: ./client
    id: client
    binary: "iom_{{ .Os }}_{{ .Arch }}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags: "-s -w"
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    no_unique_dist_dir: true

  -
    main: ./server/
    id: server
    binary: "malice_network_{{ .Os }}_{{ .Arch }}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags: "-s -w"
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    no_unique_dist_dir: true

upx:
  -
    enabled: true
    goos: [linux, windows]
    goarch:
      - amd64
      - "386"

archives:
  -
    name_template: "{{ .Binary }}"
    format: binary

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - '^MERGE'
      - "{{ .Tag }}"
      - "^docs"

release:
  github:
    owner: chainreactors
    name: malice-network
  draft: true
